/*
  GitHub Pages frontend.
  IMPORTANT: set API_BASE to the public URL where your Python app.py is running.
  Example: const API_BASE = 'https://your-bot-backend.example.com';
  When the Web App is served by the same Python server, keep API_BASE as ''.
*/
const API_BASE = '';
const tg = window.Telegram?.WebApp;
tg?.ready(); tg?.expand();

const demoCards = [
  {id:1,name:'Naruto',form:'Childhood',rarity:'Epic',attack:40,defense:35,speed:55,hp:180,energy:70,power:420,coin_price:800,qty:1,level:1,next_id:3,image_url:'./naruto_childhood.svg',ability_name:'Rasengan'},
  {id:2,name:'Sasuke',form:'Academy',rarity:'Epic',attack:42,defense:38,speed:60,hp:175,energy:75,power:430,coin_price:850,qty:1,level:1,next_id:null,image_url:'./sasuke_academy.svg',ability_name:'Fireball'},
  {id:3,name:'Kakashi',form:'Jonin',rarity:'Epic',attack:45,defense:45,speed:70,hp:190,energy:85,power:470,coin_price:950,qty:1,level:1,next_id:5,image_url:'./kakashi_jonin.svg',ability_name:'Copy'},
  {id:4,name:'Tanjiro',form:'Final Selection',rarity:'Epic',attack:47,defense:40,speed:65,hp:185,energy:80,power:460,coin_price:900,qty:1,level:1,next_id:null,image_url:'./tanjiro_final.svg',ability_name:'Water Wheel'},
  {id:5,name:'Itachi',form:'Anbu',rarity:'Legendary',attack:72,defense:68,speed:82,hp:240,energy:100,power:850,coin_price:2500,qty:0,level:1,next_id:6,image_url:'./itachi_anbu.svg',ability_name:'Amaterasu'},
  {id:6,name:'Gojo',form:'Awakened',rarity:'Mighty',attack:95,defense:91,speed:97,hp:340,energy:150,power:1800,coin_price:10000,qty:0,level:1,next_id:null,image_url:'./gojo_awakened.svg',ability_name:'Infinity'},
  {id:7,name:'Sukuna',form:'King of Curses',rarity:'Mighty',attack:98,defense:89,speed:91,hp:360,energy:155,power:1900,coin_price:12000,qty:0,level:1,next_id:null,image_url:'./sukuna_king.svg',ability_name:'Malevolent Shrine'},
  {id:8,name:'Naruto',form:'Baryon Mode',rarity:'Mighty',attack:98,defense:90,speed:99,hp:355,energy:160,power:2000,coin_price:15000,qty:0,level:1,next_id:null,image_url:'./naruto_baryon.svg',ability_name:'Baryon Mode'}
];
const demoSpells = [
  {id:1,name:'Sharingan',rarity:'Epic',chakra_cost:3,coin_price:30,power_min:10,power_max:25,image_url:'./sharingan.svg',description:'Kritik ehtimolini oshiradi.'},
  {id:2,name:'Chidori',rarity:'Epic',chakra_cost:5,coin_price:50,power_min:15,power_max:35,image_url:'./chidori.svg',description:'Tezkor elektr zarba.'},
  {id:3,name:'Rasengan',rarity:'Legendary',chakra_cost:8,coin_price:120,power_min:25,power_max:55,image_url:'./rasengan.svg',description:'Kuchli Chakra zarbasi.'},
  {id:4,name:'Amaterasu',rarity:'Legendary',chakra_cost:12,coin_price:180,power_min:35,power_max:70,image_url:'./amaterasu.svg',description:'Davomiy qora olov.'},
  {id:5,name:'Hollow Purple',rarity:'Mighty',chakra_cost:20,coin_price:400,power_min:60,power_max:100,image_url:'./hollow_purple.svg',description:'Katta maydon zarbasi.'},
  {id:6,name:'Baryon Mode',rarity:'Mighty',chakra_cost:25,coin_price:500,power_min:70,power_max:100,image_url:'./baryon_mode.svg',description:'Extreme energiya chiqaradi.'}
];
const demoUser = {id:0,coin:8500,chakra:60,cash_balance:0};
const state = {user:demoUser,cards:demoCards,spells:demoSpells,shop:null,arena:null,selected:[],opponents:demoCards.filter(c=>c.qty>0).map(c=>({card:c,opponents:demoCards.filter(x=>x.rarity===c.rarity).slice(0,2)}))};

const el = id => document.getElementById(id);
const money = n => Number(n || 0).toLocaleString('uz-UZ');
const rlabel = r => r === 'Mighty' ? '🔥 MIGHTY' : r === 'Legendary' ? '🟪 LEGENDARY' : '🟦 EPIC';
function toast(text){const t=el('toast');t.textContent=text;t.classList.add('show');clearTimeout(toast._t);toast._t=setTimeout(()=>t.classList.remove('show'),1800)}
function go(screen){document.querySelectorAll('.screen').forEach(x=>x.classList.toggle('active',x.id===screen));document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.screen===screen));if(screen==='arena')paintArena()}
document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.go)));
document.querySelectorAll('.nav').forEach(b=>b.addEventListener('click',()=>go(b.dataset.screen)));

async function api(path,opts={}){
  const url = (API_BASE || '').replace(/\/$/,'') + path;
  try{
    const r=await fetch(url,{...opts,headers:{'Content-Type':'application/json','X-Telegram-Init-Data':tg?.initData||'',...(opts.headers||{})}});
    const d=await r.json(); if(!r.ok) throw new Error(d.error||'Xatolik'); return d;
  }catch(e){if(API_BASE) throw e;return null;}
}
async function load(){
  const remoteMe=await api('/api/me');
  const remoteShop=await api('/api/shop');
  if(remoteMe){state.user=remoteMe.user;state.cards=remoteMe.cards;state.spells=remoteMe.spells}
  if(remoteShop)state.shop=remoteShop; else state.shop={cards:state.cards,spells:state.spells,chakra_packages:[{coin:100,chakra:10},{coin:500,chakra:60},{coin:1000,chakra:130}]};
  paintTop();paintHome();paintCards();paintSpells();paintShop();
}
function paintTop(){el('coin').textContent=money(state.user.coin);el('chakra').textContent=money(state.user.chakra);el('cash').textContent=money(state.user.cash_balance)+' so‘m'}
function paintHome(){const c=state.cards.filter(x=>x.qty>0);el('home-stats').innerHTML=`<div class="stat-card"><small>🎴 Kolleksiya</small><b>${c.length}</b><small>karta turi</small></div><div class="stat-card"><small>🟦 Epic</small><b>${c.filter(x=>x.rarity==='Epic').length}</b><small>Epic sahifa</small></div><div class="stat-card"><small>🟪 Legendary</small><b>${c.filter(x=>x.rarity==='Legendary').length}</b><small>Legendary sahifa</small></div><div class="stat-card"><small>🔥 Mighty</small><b>${c.filter(x=>x.rarity==='Mighty').length}</b><small>Mighty sahifa</small></div>`}
function cardHTML(c){return `<article class="card"><img src="${c.image_url}" alt="${c.name}"><span class="rarity">${rlabel(c.rarity)}</span><div class="card-body"><div class="name">${c.name} — ${c.form}</div><div class="meta">Power ${c.power} · ${c.ability_name}</div><div class="stats"><div class="mini-stat">❤️ ${c.hp}</div><div class="mini-stat">⚔️ ${c.attack}</div><div class="mini-stat">🛡 ${c.defense}</div></div><div class="meta">⚡ ${c.speed} · 🔮 ${c.energy} · Miqdor ${c.qty||0}</div><div class="price">🪙 ${money(c.coin_price)}</div><div class="mini-row">${c.next_id&&c.qty>=5?`<button class="small-btn primary" data-upgrade="${c.id}" data-mode="merge">5 ta → Upgrade</button>`:''}${c.next_id?`<button class="small-btn" data-upgrade="${c.id}" data-mode="coin">Coin bilan</button>`:''}</div></div></article>`}
function paintCards(){const rs=['Epic','Legendary','Mighty'];el('rarity-tabs').innerHTML=rs.map((r,i)=>`<button class="tab ${i?'':'active'}" data-rarity="${r}">${rlabel(r)}</button>`).join('');filterCards('Epic');document.querySelectorAll('#rarity-tabs .tab').forEach(b=>b.addEventListener('click',()=>{filterCards(b.dataset.rarity);document.querySelectorAll('#rarity-tabs .tab').forEach(x=>x.classList.remove('active'));b.classList.add('active')}));el('card-grid').addEventListener('click',async e=>{const b=e.target.closest('[data-upgrade]');if(!b)return;await upgrade(+b.dataset.upgrade,b.dataset.mode)})}
function filterCards(r){const a=state.cards.filter(x=>x.rarity===r);el('card-grid').innerHTML=a.length?a.map(cardHTML).join(''):'<div class="empty">Bu rarity sahifasi bo‘sh.</div>'}
function spellHTML(s){return `<article class="card"><img src="${s.image_url}" alt="${s.name}"><span class="rarity">${rlabel(s.rarity)}</span><div class="card-body"><div class="name">${s.name}</div><div class="meta">🔮 ${s.chakra_cost} Chakra · 🪙 ${money(s.coin_price)}</div><div class="stats"><div class="mini-stat">⚡ ${s.power_min}–${s.power_max}</div></div><div class="meta">${s.description}</div></div></article>`}
function paintSpells(){const rs=['Epic','Legendary','Mighty'];el('spell-tabs').innerHTML=rs.map((r,i)=>`<button class="tab ${i?'':'active'}" data-spell-rarity="${r}">${rlabel(r)}</button>`).join('');filterSpells('Epic');document.querySelectorAll('[data-spell-rarity]').forEach(b=>b.addEventListener('click',()=>{filterSpells(b.dataset.spellRarity);document.querySelectorAll('[data-spell-rarity]').forEach(x=>x.classList.remove('active'));b.classList.add('active')}))}
function filterSpells(r){const a=state.spells.filter(x=>x.rarity===r);el('spell-grid').innerHTML=a.length?a.map(spellHTML).join(''):'<div class="empty">Bu sahifa bo‘sh.</div>'}
function paintShop(){let h=state.shop.cards.map(c=>`<article class="shop-card"><img src="${c.image_url}" alt="${c.name}"><div class="meta">${rlabel(c.rarity)}</div><h3 style="margin:7px 0 0">${c.name} — ${c.form}</h3><div class="meta">⚔️ ${c.attack} · 🛡 ${c.defense} · ⚡ ${c.speed}</div><div class="price">🪙 ${money(c.coin_price)}</div><button class="btn primary" data-buy-card="${c.id}">Xarid qilish</button></article>`).join('');h+=`<article class="shop-card"><div class="meta">🔮 RESURS</div><h3>Chakra paketlari</h3>${state.shop.chakra_packages.map(p=>`<div class="resource"><div class="resource-row"><b>🪙 ${money(p.coin)}</b><span>→</span><b>🔮 ${money(p.chakra)}</b></div><button class="small-btn" data-buy-chakra="${p.coin}">Olish</button></div>`).join('')}</article>`;el('shop-grid').innerHTML=h;el('shop-grid').onclick=async e=>{const c=e.target.closest('[data-buy-card]');if(c)await buyCard(+c.dataset.buyCard);const ch=e.target.closest('[data-buy-chakra]');if(ch)await buyChakra(+ch.dataset.buyChakra)}}
async function refreshRemote(){const r=await api('/api/me');if(r){state.user=r.user;state.cards=r.cards;state.spells=r.spells;paintTop();paintHome();paintCards();paintSpells()}}
async function buyCard(id){const r=await api('/api/shop/card',{method:'POST',body:JSON.stringify({card_id:id})});if(r){state.user=r.user;state.cards=r.cards;paintTop();paintHome();paintCards();toast('Karta kolleksiyaga qo‘shildi.')}else{const c=state.cards.find(x=>x.id===id);if(c&&state.user.coin>=c.coin_price){state.user.coin-=c.coin_price;c.qty=(c.qty||0)+1;paintTop();paintHome();paintCards();toast('Demo rejim: karta olindi.')}else toast('Coin yetarli emas.')}}
async function buyChakra(coin){const r=await api('/api/shop/chakra',{method:'POST',body:JSON.stringify({coin})});if(r){state.user=r.user;paintTop();toast('Chakra qo‘shildi.')}else{const g={100:10,500:60,1000:130}[coin];if(g&&state.user.coin>=coin){state.user.coin-=coin;state.user.chakra+=g;paintTop();toast('Demo rejim: Chakra olindi.')}else toast('Coin yetarli emas.')}}
async function upgrade(id,mode){const r=await api('/api/cards/upgrade',{method:'POST',body:JSON.stringify({card_id:id,mode})});if(r){state.user=r.user;state.cards=r.cards;paintTop();paintHome();paintCards();toast('Upgrade bajarildi.');return}const c=state.cards.find(x=>x.id===id);if(!c||!c.next_id){toast('Bu karta upgrade qilinmaydi.');return}if(mode==='merge'&&c.qty>=5){c.qty-=5;const n=state.cards.find(x=>x.id===c.next_id);if(n)n.qty=(n.qty||0)+1}else if(mode==='coin'&&state.user.coin>=150){state.user.coin-=150;const n=state.cards.find(x=>x.id===c.next_id);if(n)n.qty=(n.qty||0)+1;c.qty-=1}else{toast('Shartlar yetarli emas.');return}paintTop();paintHome();paintCards();toast('Demo rejim: upgrade bajarildi.')} 
async function paintArena(){const r=await api('/api/arena/opponents');if(r)state.opponents=r.cards;else state.opponents=state.cards.filter(x=>x.qty>0).map(c=>({card:c,opponents:state.cards.filter(x=>x.rarity===c.rarity).slice(0,2)}));el('arena-setup').innerHTML=`<div class="arena-setup glass"><div class="section-head" style="margin:0 0 10px"><div><h2 style="font-size:19px">Jamoani tanlang</h2><p>5 ta karta. Har bir karta uchun 2 ta yaqin raqib.</p></div><span class="tag">⏱ 60 soniya</span></div><div class="select-grid">${state.opponents.slice(0,12).map(x=>`<div class="slot"><img src="${x.card.image_url}" alt=""><b>${x.card.name}</b><div class="meta">${rlabel(x.card.rarity)} · ${x.card.power}</div><button class="small-btn" data-select="${x.card.id}">${state.selected.some(s=>s.card.id===x.card.id)?'✓ Tanlangan':'Tanlash'}</button></div>`).join('')}</div><div id="chosen" class="mini-row"></div><button class="btn primary" id="start-arena">⚔️ Jangni boshlash</button></div>`;el('arena-setup').querySelectorAll('[data-select]').forEach(b=>b.onclick=()=>selectArena(+b.dataset.select));el('start-arena').onclick=startArena;el('chosen').innerHTML=state.selected.map((x,i)=>`<span class="tag">${i+1}. ${x.card.name}</span>`).join('')}
function selectArena(id){const f=state.opponents.find(x=>x.card.id===id);if(!f)return;if(state.selected.some(x=>x.card.id===id))state.selected=state.selected.filter(x=>x.card.id!==id);else if(state.selected.length<5)state.selected.push(f);paintArena()}
async function startArena(){if(state.selected.length!==5){toast('5 ta karta tanlang.');return}const r=await api('/api/arena/start',{method:'POST',body:JSON.stringify({card_ids:state.selected.map(x=>x.card.id),opp_ids:state.selected.map(x=>x.opponents?.[0]?.id)})});if(r)state.arena=r;else state.arena=demoArena();state.selected=[];renderArena()}
function demoArena(){const team=state.cards.filter(x=>x.qty>0).slice(0,5);const opp=team.map(x=>state.cards.find(y=>y.rarity===x.rarity&&y.id!==x.id)||x);return {match:{id:'demo',finished:0,total_user_hp:team.reduce((a,b)=>a+b.hp,0),total_opp_hp:opp.reduce((a,b)=>a+b.hp,0)},team,opponents:opp,remaining:60,events:[{text:'⚔️ Arena boshlandi. Demo rejim.',turn_no:0}]}}
function renderArena(){const m=state.arena.match;el('arena-live').innerHTML=`<div class="arena-board"><div><b>Sizning jamoa</b><div class="team">${state.arena.team.map(x=>`<div class="slot"><img src="${x.image_url}" alt=""><b>${x.name}</b></div>`).join('')}</div></div><div class="vs">VS</div><div><b>Raqib jamoa</b><div class="team">${state.arena.opponents.map(x=>`<div class="slot"><img src="${x.image_url}" alt=""><b>${x.name}</b></div>`).join('')}</div></div></div><div class="hero glass" style="min-height:0;margin-top:12px;display:block;padding:15px;background-image:none"><div class="timer"><b id="arena-timer">${state.arena.remaining||60}</b></div>${m.finished?'':'<div class="select-grid">'+state.arena.opponents.map((x,i)=>`<div class="slot"><img src="${x.image_url}" alt=""><b>${x.name}</b><button class="small-btn primary" data-move="${i}">Shunga hujum</button></div>`).join('')+'</div>'}<div class="log">${state.arena.events.slice().reverse().map(e=>`<div class="event">${e.text}</div>`).join('')}</div></div>`;el('arena-live').querySelectorAll('[data-move]').forEach(b=>b.onclick=()=>moveArena(+b.dataset.move));if(!m.finished&&state.arena.match.id!=='demo')tickArena()}
let timerId;function tickArena(){clearInterval(timerId);timerId=setInterval(async()=>{const r=await api('/api/arena/'+state.arena.match.id+'/state');if(r){state.arena=r;const t=el('arena-timer');if(t)t.textContent=r.remaining;if(r.match.finished){clearInterval(timerId);renderArena()}}},1000)}
async function moveArena(index){const r=await api('/api/arena/'+state.arena.match.id+'/move',{method:'POST',body:JSON.stringify({opp_index:index})});if(r){state.arena=r;renderArena()}else{toast('Demo rejim: yurish bajarildi.')}}
load().catch(e=>{console.error(e);toast('Demo rejim yoqildi')});
